define([], function () {
    return {
        english: {
            actionsTitle: '',
            actionsText: '',
            submitTitle: 'Submit - This button has shortcut [m]',
            submitText: 'Submit',
            validateTitle: 'Validate - This button has shortcut [l]',
            validateText: 'Validate',
            printTitle: 'Print - This button has shortcut [p]',
            printText: 'Print',
            saveAsPDFTitle: 'Save as Pdf - This button has shortcut [c]',
            saveAsPDFText: 'Save as Pdf',
            fullViewTitle: 'Full view - This button has shortcut [r]',
            fullViewText: 'Full view',
            tabsTitle: 'Tabs view - This button has shortcut [x]',
            tabsText: 'Tabs view',
            helpAndInfoTitle: 'Help & Info - This button has shortcut [y]',
            helpAndInfoText: 'Help & Info',
            printMessage: 'Sending to print',
            savingActionsTitle: 'Saving actions',
            additionalActions: 'Other actions',
            viewSectionTitle: 'Display options',
            saveTitle: 'Save - This button has shortcut [s]',
            saveText: 'Save',
            restoreTitle: 'Restore -  This button has shortcut',
            restoreText: 'Restore',
            fileAttachmentText: 'Attachment',
            fileAttachmentTitle: 'Attachment - This button has shortcut [j]'

        },
        hebrew: {
            actionsTitle: 'פעולות - לכפתור זה קיים קיצור דרך [z]',
            actionsText: 'פעולות',
            submitTitle: 'שלח - לכפתור זה קיים קיצור דרך [m]',
            submitText: 'שלח',
            validateTitle: 'בדוק תקינות - לכפתור זה קיים קיצור דרך [l]',
            validateText: 'בדוק תקינות',
            printTitle: 'הדפס - לכפתור זה קיים קיצור דרך [p]',
            printText: 'הדפס',
            saveAsPDFTitle: 'שמור כ-PDF - לכפתור זה קיים קיצור דרך [c]',
            saveAsPDFText: 'שמור כ-PDF',
            fullViewTitle: 'תצוגה מלאה - לכפתור זה קיים קיצור דרך [r]',
            fullViewText: 'תצוגה מלאה',
            tabsTitle: 'תצוגת כרטסות - לכפתור זה קיים קיצור דרך [x]',
            tabsText: 'תצוגת כרטסות',
            helpAndInfoTitle: 'עזרה ומידע - לכפתור זה קיים קיצור דרך [y]',
            helpAndInfoText: 'עזרה ומידע',
            printMessage: 'שולח להדפסה',
            savingActionsTitle: 'אפשרויות שמירה',
            additionalActions: 'פעולות נוספות',
            viewSectionTitle: 'אפשרויות תצוגה',
            saveTitle: 'שמור - לכפתור זה קיים קיצור דרך [s]',
            saveText: 'שמור',
            restoreTitle: 'פתיחת שירות שמור - לכפתור זה קיים קיצור דרך [s]',
            restoreText: 'פתיחת שירות שמור',
            fileAttachmentText: 'צרופות',
            fileAttachmentTitle: 'צרופות - לכפתור זה קיים קיצור דרך [j]'

        },
        arabic: {
            actionsTitle: '',
            actionsText: '',
            submitTitle: 'שלח - לכפתור זה קיים קיצור דרך [m]',
            submitText: 'שלח',
            validateTitle: 'בדוק תקינות - לכפתור זה קיים קיצור דרך [l]',
            validateText: 'בדוק תקינות',
            printTitle: 'הדפס - לכפתור זה קיים קיצור דרך [p]',
            printText: 'הדפס',
            saveText:'שמור',
            saveAsPDFTitle: 'שמור כ-PDF - לכפתור זה קיים קיצור דרך [c]',
            saveAsPDFText: 'שמור כ-PDF',
            fullViewTitle: 'תצוגה מלאה - לכפתור זה קיים קיצור דרך [r]',
            fullViewText: 'תצוגה מלאה',
            tabsTitle: 'תצוגת כרטסות - לכפתור זה קיים קיצור דרך [x]',
            tabsText: 'תצוגת כרטסות',
            helpAndInfoTitle: 'עזרה ומידע - לכפתור זה קיים קיצור דרך [y]',
            helpAndInfoText: 'עזרה ומידע',
            printMessage: 'أرسل للطباعة',
            savingActionsTitle: 'خيارات الحفظ',
            additionalActions: 'عمليات اضافية',
            viewSectionTitle: 'خيارات العرض',
            saveTitle: 'שמור - לכפתור זה קיים קיצור דרך [s]',
            fileAttachmentText: ''
        }

    };

});