define(['common/core/govFormsInformation'], function (govFormsInformation) {
    const govFormsInfo = govFormsInformation.getFormParams();

    return {
        english: {
            notice: 'You can get a link to your saved form by email, or SMS to your mobile.',
            selectOption: 'Choose how you would like to receive the link.',
            inEmail: 'Email',
            inSMS: 'SMS',
            saveByEmailTitle: 'Get link by email',
            insertEmail: 'Enter your email.',
            validateEmail: 'Confirm your email',
            confirm: 'Confirm',
            insertedEmail: 'כתובת הדואר האלקטרוני שהזנתם:',
            formSavedNotice: 'A link to your saved form has been sent.',
            formSavedLatencyNotice: `You will be able to use the link for ${govFormsInfo.formMetadata.saveLatency} days.`,
            resend: 'לשליחה חוזרת',
            saveBySMS: 'Get link by SMS',
            insertPhoneNumber: 'Enter your mobile number',
            validatePhoneNumber: 'Confirm your mobile number',
            insertedPhone: 'מספר הטלפון שהזנתם:',
            emailPlaceholder: '@',
            saveFormTitle: 'Save form',
            cancelButton: 'Cancel',
            emailValidationError: 'You must enter the same details from the previous field.',
            cancelMessage: 'Are you sure you want to exit without sending? ',
            emailValidationMessage: 'You must enter the same details from the previous field.',
            manualTyping: 'You cannot paste details into this field.',
            emailIsRequire: 'Your email address is not valid. Please type again to send.',
            cellNumberIsRequire: 'בכדי לשלוח הודעה יש להזין ערך תקין בשדות הטלפון',
            pending: 'פעולת השמירה מתבצעת'
        },
        hebrew: {
            notice: 'קישור לשירות ששמרתם ישלח אליכם מיד',
            selectOption: 'בחרו את הדרך בה תרצו לקבל את הקישור:',
            inEmail: 'בדואר אלקטרוני',
            inSMS: 'במסרון',
            saveByEmailTitle: 'קבלת קישור לשירות באמצעות דואר אלקטרוני',
            insertEmail: 'הזינו כתובת דואר אלקטרוני',
            validateEmail: 'אמתו את כתובת הדואר האלקטרוני',
            confirm: 'אישור',
            insertedEmail: 'כתובת הדואר האלקטרוני שהזנתם:',
            formSavedNotice: 'קישור לשירות ששמרתם נשלח לפי בקשתכם.',
            formSavedLatencyNotice: ` פתיחת השירות אפשרית למשך ${govFormsInfo.formMetadata.saveLatency} ימים.`,
            resend: 'לשליחה חוזרת',
            saveBySMS: 'קבלת קישור לשירות באמצעות מסרון',
            insertPhoneNumber: 'הזינו מספר טלפון נייד',
            validatePhoneNumber: 'אמתו את מספר הטלפון הנייד',
            insertedPhone: 'מספר הטלפון שהזנתם:',
            manualTyping: 'עליך להזין ערך בשדה זה ידנית',
            saveFormTitle: 'שמירה',
            emailPlaceholder: '@',
            cancelButton: 'ביטול',
            emailValidationError: 'יש להזין ערך זהה לערך בשדה קודם',
            cancelMessage: 'האם אתה בטוח שברצונך לצאת ללא שליחת הודעה?',
            emailValidationMessage: 'יש להזין ערך זהה לערך בשדה קודם',
            emailIsRequire: 'בכדי לשלוח הודעה יש להזין ערך תקין בשדות המייל',
            cellNumberIsRequire: 'בכדי לשלוח הודעה יש להזין ערך תקין בשדות הטלפון',
            pending: 'פעולת השמירה מתבצעת'
        },
        arabic: {
            notice: 'קישור לשירות ששמרתם ישלח אליכם מיד',
            selectOption: 'בחרו את הדרך בה תרצו לקבל את הקישור:',
            inEmail: 'בדואר אלקטרוני',
            inSMS: 'במסרון',
            saveByEmailTitle: 'שמירה באמצעות דואר אלקטרוני',
            insertEmail: 'הזינו כתובת דואר אלקטרוני',
            validateEmail: 'אמתו את כתובת הדואר האלקטרוני',
            confirm: 'אישור',
            insertedEmail: 'כתובת הדואר האלקטרוני שהזנתם:',
            formSavedNotice: 'קישור לשירות ששמרתם נשלח לפי בקשתכם.',
            formSavedLatencyNotice: ` פתיחת השירות אפשרית למשך ${govFormsInfo.formMetadata.saveLatency} ימים.`,
            resend: 'לשליחה חוזרת',
            saveBySMS: 'שמירה באמצעות מסרון',
            insertPhoneNumber: 'הזינו מספר טלפון נייד',
            validatePhoneNumber: 'אמתו את מספר הטלפון',
            insertedPhone: 'מספר הטלפון שהזנתם:',
            manualTyping: 'עליך להזין ערך בשדה זה ידנית',
            saveFormTitle: 'שמירה',
            emailPlaceholder: '@',
            cancelButton: 'ביטול',
            emailValidationError: 'יש להזין ערך זהה לערך בשדה קודם',
            cancelMessage: 'האם אתה בטוח שברצונך לצאת ללא שליחת הודעה?',
            emailValidationMessage: 'יש להזין ערך זהה לערך בשדה קודם',
            emailIsRequire: 'בכדי לשלוח הודעה יש להזין ערך תקין בשדות המייל',
            cellNumberIsRequire: 'בכדי לשלוח הודעה יש להזין ערך תקין בשדות הטלפון',
            pending: 'פעולת השמירה מתבצעת'
        }

    };

});